title: Haptic khipu
description: This project investigates a late Inka, early Colonial khipu in UC Santa
  Barbara’s Art, Design & Architecture Museum through material, haptic, and digital
  imaging methods to explore how Andean recordkeeping systems encode knowledge in
  fiber and form.
baseurl: /story
url: https://mirl-ucsb.github.io
author: Alicia Boswell, Alida Jekabson, Izzy Devlin, Jeff O’Brien, María Lumbreras,
  Juan Cobo Betancourt
email: mirl@arthistory.ucsb.edu
telar_theme: neogranadina
logo: ''
telar_language: en
story_interface:
  show_story_steps: true
  include_demo_content: false
google_sheets:
  enabled: true
  shared_url: https://docs.google.com/spreadsheets/d/1jsL_FovT5JCsTBk7Qz_iSJNsDuY5wt-h6o1lAfbJ1D8/edit
  published_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vTodWYk4eyiNgqnP3s499aY-AhsLoSyAVbDpX7gCNTnOHVRqOt-8TKOOL50rU8nQUHq-vj0C7JucEqC/pubhtml
collections:
  stories:
    output: true
    permalink: /stories/:name/
  objects:
    output: true
    permalink: /objects/:name/
  glossary:
    output: true
    permalink: /glossary/:name/
collections_dir: _jekyll-files
markdown: kramdown
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor
- .github
- README.md
- docs/
- scripts/
defaults:
- scope:
    path: ''
    type: stories
  values:
    layout: story
- scope:
    path: ''
    type: objects
  values:
    layout: object
- scope:
    path: ''
    type: glossary
  values:
    layout: glossary
future: true
show_drafts: false
telar:
  version: 0.4.0-beta
  release_date: $(date +%Y-%m-%d)
plugins:
- jekyll-seo-tag
webrick:
  headers:
    Access-Control-Allow-Origin: '*'
    Access-Control-Allow-Methods: GET, POST, OPTIONS
    Access-Control-Allow-Headers: Content-Type
